/** 🌹oddFEELING */

import Head from 'next/head';
import { useState } from 'react';
import { visibleState } from '../global/state.global';
import ModalComponent from '../components/Modal.component';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [del, setDelete] = useState(true);
  const { setVisible } = visibleState();

  //=============================================>  props declaration
  // ======= Delete props -->
  const DeleteProps = {
    top_text: 'The User has clicked Delete',
    btn_click: () => {
      alert('OTP for delete sent');
    },
    btn_text: 'Delete',
  };

  // ======= Disable props -->
  const DisableProps = {
    top_text: 'The user has clicke Disable',
    btn_click: () => {
      alert('OTP for disable sent');
    },
    btn_text: 'Disable',
  };

  //=============================================>  clicks
  // ======= continue clkick -->
  const handleContinue = () => {
    setVisible();
  };

  // ======= delete click -->
  const handleDelete = () => {
    setDelete((del) => true);
  };

  // ======= disable click -->
  const handleDisable = () => {
    setDelete((del) => false);
  };

  //=============================================>  effects
  // useEffect(() => {
  //   console.log(`Delete state has changed`);
  // }, [del]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.option__div}>
          <button onClick={handleDelete}> Delete</button>
          <button onClick={handleDisable}>Disable</button>
          <button onClick={handleContinue}>Continue</button>
        </div>

        <ModalComponent
          props={del ? { ...DeleteProps } : { ...DisableProps }}
        />
      </main>
    </div>
  );
}
